
services:
  agp_gateway:
    image: ghcr.io/agntcy/agp/gw:latest
    container_name: agp_gateway
    ports:
      - "46357:46357"
    environment:
      - PASSWORD=${PASSWORD:-dummy}  # Default password if not set
    volumes:
      - ./gw/config/base/server-config.yaml:/config.yaml
    command: ["/gateway", "--config", "/config.yaml"]
    restart: unless-stopped
    networks:
      - agp_network  # Ensure both services are on the same network

  agp_remote_agent:
    build:
      context: .  # Set project root as the build context
      dockerfile: remote_agent_docker/Dockerfile  # Dockerfile is inside remote_agent_docker/
    container_name: agp_remote_agent
    depends_on:
      - agp_gateway
    environment:
      - AGP_ADDRESS=http://agp_gateway  # Inside Compose, use agp_gateway
    env_file:
      - ../.env
    volumes:
      - ../.env:/app/.env  # <== This explicitly mounts .env at /app/.env      
    networks:
      - agp_network
    restart: unless-stopped

networks:
  agp_network:
    driver: bridge
